grpc:
  server:
    port: 6566

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grpc
    username: justin
    password: Shannon2010@
    driverClassName: com.mysql.cj.jdbc.Driver
    data: data.sql

  jpa:
    hibernate:
      ddl-auto: update
    #properties: 'org.hibernate.dialect.MySQL8Dialect'

server:
  port: 9090